# Generated by Django 2.2.19 on 2022-10-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
